### ISSUE TITLE
freezeColors license?

### ISSUE THREAD

**Issue by mgali** [jiversen/freezeColors#2]
I used freezeColors in a project that became a publication (thanks for making this public!). I finally decided to bundle together all my Matlab code and the extra packages I used used so people could reproduce my calculations and figures.

Issue: when uploading my "code package" onto a repository (Dryad) they noted the following:

> "The freezeColors directory contains a full copyright statement that's framed as a license, but it doesn't list any license by name (this may be the copyright holder not really understanding how licensing works and trying to prescribe something outside of the existing legal framework). This one would be very complicated to redistribute anywhere because of the lack of a specified license and the requirement of practically every data repository to prescribe a specific license (general conditions are not sufficient). For example, if you went to Zenodo or figshare, they will still ask you how to license it, and you would need to license it with something that fulfills the criteria prescribed in the license file. Either way, that directory is not compatible with CC0 because the creator is retaining copyright, and you cannot public domain designate somebody else's copyrighted work. "

A clarification of the licensing conditions would be useful! Thanks

**Comment by jiversen** [comment]
Thanks for the heads up and detailed example. I've added a license.
